SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE RIGHTS;
INSERT INTO RIGHTS VALUES('Admin', 1, 1, 1,	1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO RIGHTS VALUES('Buchhaltung', 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0);
INSERT INTO RIGHTS VALUES('Polier', 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0);
INSERT INTO RIGHTS VALUES('Werkstatt', 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1);

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE DEVICE_STATUS;
INSERT INTO  DEVICE_STATUS (description)  VALUES ('Verfügbar');
INSERT INTO  DEVICE_STATUS (description)  VALUES ('Ausgeliehen');
INSERT INTO  DEVICE_STATUS (description)  VALUES ('In Wartung');
INSERT INTO  DEVICE_STATUS (description)  VALUES ('Außer Betrieb');
INSERT INTO  DEVICE_STATUS (description)  VALUES ('Defekt');
INSERT INTO  DEVICE_STATUS (description)  VALUES ('Verschollen/Verschwunden');
INSERT INTO  DEVICE_STATUS (description)  VALUES ('Gestohlen');


SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE CATEGORY;
INSERT INTO CATEGORY VALUES('0001','Rüttelplatten');
INSERT INTO CATEGORY VALUES('0002','Stampfer');
INSERT INTO CATEGORY VALUES('0003','Motorflex');
INSERT INTO CATEGORY VALUES('0004','Rohrgreifer');
INSERT INTO CATEGORY VALUES('0005','Kettensägen');
INSERT INTO CATEGORY VALUES('0006','Motorhammer');
INSERT INTO CATEGORY VALUES('0007','Leiter');
INSERT INTO CATEGORY VALUES('0008','Exoten');
INSERT INTO CATEGORY VALUES('FFFF','Nicht gesetzt');

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE BEACON;
INSERT INTO BEACON VALUES('DA95206921ED84C1ED97EA92306C5A7F', '0007', '0001');
